## 1. Import numpy as np and see the version

## 2. How to create a boolean array?

Q. Create a 3×3 numpy array of all True’s

## 3. How to replace items that satisfy a condition with another value in numpy array?

Q. Replace all odd numbers in arr with -1

</br>
</br>

Input:
</br>

`
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
`

</br>
</br>

Desired output:
</br>

`
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
`

## 4. How to reshape an array?
Q. Convert a 1D array to a 2D array with 2 rows

</br>
</br>

Input:
</br>

`
arr = np.arange(10)
`

</br>
</br>

Desired output:
</br>

`
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
`

## 5. How to get the positions of top n values from a numpy array?
Q. Get the top 5 maximum values in a given array a.
</br>
</br>

Input:
</br>

`
arr = np.array([9, 3, 19, 26, 1, 97, 2, 14, 44, 120])
`

</br>
</br>

Desired output:
</br>

`
#> array([120,97, 44, 26, 19])
`

## 6. How to compare two arrays using indexing?
Q. How to get array of equal values comparing two other arrays?
</br>
</br>

Input:
</br>

`
a = np.array([5, 0, 2, 1, 4, 3])
b = np.array([6, 0, 4, 1, 9, 3 ])
`

</br>
</br>

Desired output:
</br>

`
#> array([0, 1, 3])
`