# Importing Numpy

In [67]:
import numpy as np

# Creating Arrays

In [36]:
# create 1d array
x = [1,2,3]
a = np.array(x)
a

array([1, 2, 3])

In [ ]:
[1, 1.5, 'string']

In [72]:
# create 2d array
x = [(1.5,2,'3'), (4,5,6)]

b = np.array(x)
b

array([['1.5', '2', '3'],
       ['4', '5', '6']], dtype='<U32')

In [4]:
# create 3d array

c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

# Initial Placeholders

In [5]:
# create array of zeros

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
# create array of ones

np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [70]:
# Create an array in a certain range

np.arange(0,12,5)

array([ 0,  5, 10])

In [3]:
# Create an array of evenly spaced values (number of samples)

np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [73]:
# Create a constant array

np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [74]:
# Create an identity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
# Create an array with random values

np.random.rand(3,2) # 0, 1

array([[0.25499684, 0.72838044],
       [0.00646326, 0.10123371],
       [0.8850903 , 0.0264277 ]])

In [41]:
np.random.randint(1,(5,5))

array([[3, 1, 1, 2, 4],
       [2, 3, 2, 4, 2],
       [4, 3, 1, 3, 1],
       [2, 3, 1, 1, 1],
       [2, 3, 2, 4, 1]])

# Inspecting Your Array

In [80]:
a = np.array([[1,2,3],[4,5,6]], dtype = float)

In [77]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
# Array dimensions

a.shape

(2, 3)

In [12]:
# Length of array

len(a)

2

In [13]:
# Number of dimensions of the array

a.ndim

2

In [14]:
# Number of array elements

a.size

6

In [47]:
# Data type of array elements

a.dtype

dtype('float64')

In [81]:
# Convert an array to a different type

a.astype(str)

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0']], dtype='<U32')

# Array Mathematics

## Arithmetic Operations

In [92]:
a = np.array([3,1,3])

b = np.array([(1,9,2),
              (6,4,5)], dtype = float)

In [93]:
print('This is a shape = ',a.shape)
print('This is b shape = ',b.shape)

This is a shape =  (3,)
This is b shape =  (2, 3)


In [94]:
a - b

array([[ 2., -8.,  1.],
       [-3., -3., -2.]])

In [56]:
np.subtract(a,b)

array([[ 1.5, -8. ,  0. ],
       [-3. , -3. , -3. ]])

In [57]:
b + a

array([[ 4.5, 10. ,  4. ],
       [ 9. ,  5. ,  7. ]])

In [58]:
np.add(b,a)

array([[ 4.5, 10. ,  4. ],
       [ 9. ,  5. ,  7. ]])

In [59]:
a / b

array([[2.        , 0.11111111, 1.        ],
       [0.5       , 0.25      , 0.4       ]])

In [60]:
np.divide(a,b)

array([[2.        , 0.11111111, 1.        ],
       [0.5       , 0.25      , 0.4       ]])

In [61]:
a * b

array([[ 4.5,  9. ,  4. ],
       [18. ,  4. , 10. ]])

In [62]:
np.multiply(a,b)

array([[ 4.5,  9. ,  4. ],
       [18. ,  4. , 10. ]])

In [63]:
# e^b (element wise Exponentiation)

np.exp(b)

array([[4.48168907e+00, 8.10308393e+03, 7.38905610e+00],
       [4.03428793e+02, 5.45981500e+01, 1.48413159e+02]])

In [64]:
# Element wise square root

np.sqrt(b)

array([[1.22474487, 3.        , 1.41421356],
       [2.44948974, 2.        , 2.23606798]])

## Comparison

In [100]:
x = np.array([3,4])

y = np.array([(3,4), (5,6)])

In [104]:
# Element wise comparison
x == y

z = np.array([[ True,  True],
       [False, False]])
z[z]

array([ True,  True])

In [48]:
# Element wise comparison

x < 2

array([False, False])

## Aggregate Functions

In [49]:
a = np.array([3,1,2])

b = np.array([(1.5,9,2),
              (6  ,5,4)], dtype = float)

In [50]:
# Array wise sum

b.sum()

27.5

In [77]:
# Array wise minimum value

b.min()

1.5

In [78]:
# Array wise maximum value

b.max()

9.0

In [83]:
a.mean()

2.0

In [85]:
# not available as b.median()
np.median(b)

4.5

In [86]:
np.std(b)

2.5235006549544536

# Sorting Arrays

In [110]:
a = np.array([3,1,2])

a.sort()
a

array([1, 2, 3])

# Subsetting, Slicing, Indexing

## Subsetting

In [56]:
a = np.array([[1,2,3], [4,5,6]])

a[0:1,0:1]

4

In [96]:
b = np.array([(1,2,3), (4,5,6), (6,7,8)], dtype=int)
b

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [97]:
b[1:,1:]

array([[5, 6],
       [7, 8]])

In [101]:
# Select the element at the 2nd index

a[2]

3

In [102]:
# Select the element at row 1 column 2 (equivalent to b[1][2])

b[1,2]
b[1][2]

5.0

## Slicing

In [104]:
# Select items at index 0 and 1

a[0:2]

array([1, 2])

In [105]:
# Select items at rows 0 and 1 in column 1

b[1,0:2]

array([6., 4.])

In [108]:
# Select all items at row 0 (equivalent to b[0:1, :]) Same as [1,:,:]

b[:]

array([[1.5, 9. , 2. ],
       [6. , 4. , 5. ]])

In [109]:
# reverse the array

a[ : :-1]

array([3, 2, 1])

## Boolean Indexing

In [58]:
# Select elements from a less than 3
a = np.array([[1,2,3],[1,2,6]])

a[a<3]

array([1, 2, 1, 2])

# Array Manipulation

## Transposing Array

In [113]:
# transposing the array
b = np.array([(1.5,9,2),
              (6  ,4,5)], dtype = float)
i = np.transpose(b)
i

array([[1.5, 6. ],
       [9. , 4. ],
       [2. , 5. ]])

In [114]:
# also transposing the array

i.T

array([[1.5, 9. , 2. ],
       [6. , 4. , 5. ]])

## Changing Array Shape

In [118]:
b = np.array([[1,2,3],[4,5,6]])

In [119]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
b.shape

(2, 3)

In [121]:
b.size

6

In [122]:
# Reshape, but don’t change data

#np.reshape(b, ())

b.reshape(3, -1)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
# Return a new array with shape (6, 1)

b.resize((6,1))
b

array([[1.5],
       [9. ],
       [2. ],
       [6. ],
       [5. ],
       [4. ]])

In [ ]:
np.resize()